### ISSUE TITLE
Compilation Error in Xamarin.Android Same project 

### ISSUE THREAD

**Issue by AnnuRArya** [vmwareairwatchsdk/Xamarin-AWSDK#12]
VisualStudio 2017 
Xamarin.Android 9.1.7.0
.Net Framework 4.8.03572  

I am running to this exception with same project nothings is changed ...

 Exception in thread "main" java.lang.NoClassDefFoundError: com/airwatch/sdk/AirWatchSDKException
1>  	at java.lang.Class.getDeclaredMethods0(Native Method)
1>  	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
1>  	at java.lang.Class.getDeclaredMethods(Class.java:1975)
1>  	at com.google.devtools.build.android.desugar.LambdaDesugaring.findTargetMethod(LambdaDesugaring.java:320)
1>  	at com.google.devtools.build.android.desugar.LambdaDesugaring.queueUpBridgeMethodIfNeeded(LambdaDesugaring.java:229)
1>  	at com.google.devtools.build.android.desugar.LambdaDesugaring.access$200(LambdaDesugaring.java:53)
1>  	at com.google.devtools.build.android.desugar.LambdaDesugaring$InvokedynamicRewriter.visitInvokeDynamicInsn(LambdaDesugaring.java:406)
1>  	at org.objectweb.asm.ClassReader.a(Unknown Source)
1>  	at org.objectweb.asm.ClassReader.b(Unknown Source)
1>  	at org.objectweb.asm.ClassReader.accept(Unknown Source)
1>  	at org.objectweb.asm.ClassReader.accept(Unknown Source)
1>  	at com.google.devtools.build.android.desugar.Desugar.desugarClassesInInput(Desugar.java:401)
1>  	at com.google.devtools.build.android.desugar.Desugar.desugarOneInput(Desugar.java:326)
1>  	at com.google.devtools.build.android.desugar.Desugar.desugar(Desugar.java:280)
1>  	at com.google.devtools.build.android.desugar.Desugar.main(Desugar.java:584)
1>  Caused by: java.lang.ClassNotFoundException: Class com.airwatch.sdk.AirWatchSDKException not found
1>  	at com.google.devtools.build.android.desugar.HeaderClassLoader.findClass(HeaderClassLoader.java:53)
1>  	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
1>  	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
1>  	... 15 more
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2525,3): error : java.lang.NoClassDefFoundError :  com/airwatch/sdk/AirWatchSDKException
![Capture](https://user-images.githubusercontent.com/47095702/87118757-ce96de00-c299-11ea-9fed-65a893ec0800.PNG)

**Comment by Maddy79** [comment]
Please use VS2019, this is the requirement for building the Android WS1 Xamarin SDK
